### ISSUE TITLE
Nil pointer dereference

### ISSUE THREAD

**Issue by matlapo** [justmiles/go-markdown2confluence#32]
Hi, thanks for making this!

I was trying it out and got a segmentation violation, I'm including the whole output here if that helps. I'll try to debug it, but if this is a known issue or there's a problem with the way I'm using this tool, let me know!

```
:) confluence-experiment % docker run -v ~/Projects/confluence-experiment/go-markdown2-confluence/:/tmp justmiles/markdown2confluence -e "http://localhost:8090/display/TAS/" --space "TAS" --username "admin" --password "foo" --parent "1-Projects" /tmp

localhost:8090/display/TAS/" --space "TAS" --username "admin" --password "foo" --parent "1-Projects" /tmp
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x6de8b9]

goroutine 1 [running]:
github.com/justmiles/go-confluence.(*Client).request(0xc00022c140, 0x94ace6, 0x3, 0x9520bb, 0x11, 0xc00020c540, 0x3d, 0x0, 0x0, 0x0, ...)
	/go/src/vendor/github.com/justmiles/go-confluence/client.go:52 +0x489
github.com/justmiles/go-confluence.(*Client).GetContent(0xc00022c140, 0xc00001e240, 0x7ffc01a9ef74, 0xa, 0xd6cf80, 0x0, 0xc00025bca0)
	/go/src/vendor/github.com/justmiles/go-confluence/content.go:23 +0x10c
github.com/justmiles/go-markdown2confluence/lib.(*MarkdownFile).FindOrCreateAncestor(0xc00033fb58, 0xd41580, 0xc00022c140, 0x0, 0x0, 0x7ffc01a9ef74, 0xa, 0xc00033f960, 0x45f240, 0xc00033f9a8, ...)
	/go/src/lib/file.go:167 +0x138
github.com/justmiles/go-markdown2confluence/lib.(*MarkdownFile).FindOrCreateAncestors(0xc00033fb58, 0xd41580, 0xd41580, 0xc0001e7800, 0xc00000e118, 0xc000226ce0)
	/go/src/lib/file.go:140 +0xab
github.com/justmiles/go-markdown2confluence/lib.(*Markdown2Confluence).Run(0xd41580, 0x0, 0x0, 0x0)
	/go/src/lib/markdown.go:217 +0x44d
github.com/justmiles/go-markdown2confluence/cmd.glob..func1(0xd3a5e0, 0xc00011a370, 0x1, 0xb)
	/go/src/cmd/root.go:45 +0xf7
github.com/spf13/cobra.(*Command).execute(0xd3a5e0, 0xc00001e0d0, 0xb, 0xb, 0xd3a5e0, 0xc00001e0d0)
	/go/src/vendor/github.com/spf13/cobra/command.go:766 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xd3a5e0, 0x45, 0xc00033ff48, 0x441f4a)
	/go/src/vendor/github.com/spf13/cobra/command.go:850 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/vendor/github.com/spf13/cobra/command.go:800
github.com/justmiles/go-markdown2confluence/cmd.Execute(0xa1c1e8, 0x6)
	/go/src/cmd/root.go:62 +0x8a
main.main()
	/go/src/main.go:11 +0x39
```

**Comment by matlapo** [comment]
I wasn't using Confluence Cloud 🤦
